---
title: "Assignment 2 - Almond Yield"
author: "Genevieve Chiong"
date: "4/9/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(patchwork)

source(here("R/almond_yield.R"))
```


```{r}
# read in the clim data 
clim_original <- read_delim(here("data", "clim_original.txt"), delim = " ")
clim <- read_delim(here("data", "clim.txt"), delim = " ")
```

```{r}
yield_anomalies <- almond_yield(clim)

yield_anomalies %>% knitr::kable()
```

The above table shows annual almond yield anomaly estimated by linear regression using precipitation and temperature data.


```{r}
yield_plot <- ggplot(yield_anomalies, aes(x = year, y = yield)) +
  geom_line() +
  labs(title = "Annual almond yield anomalies", y = "Yield (tons/acre)", x = "Year", tag = "a") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
sum_precip <- clim %>% 
  filter(month == 1) %>% 
  group_by(year, month) %>% 
  summarize(sum_precip = sum(precip))

mean_min_temp <- clim %>% 
  filter(month == 2) %>% 
  group_by(year, month) %>% 
  summarize(mean_min_temp = mean(tmin_c))
```

```{r}
precip_plot <- ggplot(sum_precip, aes(x = year, y = sum_precip)) +
  geom_line() +
  labs(title = "January Precip", y = "Precip (mm)", x = "Year", tag = "b") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

temp_plot <- ggplot(mean_min_temp, aes(x = year, y = mean_min_temp)) +
  geom_line() +
  labs(title = "February mean min temperatures", y = "Mean min \n Feb temp (ºC)", x = "Year", tag = "c") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
yield_plot / precip_plot / temp_plot
```


Plot (a) shows estimated annual almond yield anomaly based on temperature and precipitation data. 
Plot (b) shows summed precipitation in January of each year. 
Plot (c) shows mean minimum daily temperatures in February of each year.







