---
title: "Almond Yield and Profit Model"
author: "Genevieve Chiong"
date: "4/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(patchwork)
library(kableExtra)

source(here("R/gen_almond_yield.R"))
source(here("R/compute_almond_profit.R"))
source(here("R/compute_NPV.R"))
```

```{r}
# read in and clean data 
clim <- read.table(here("data", "clim_original.txt")) %>% 
  clean_names() 

# find temperature in February
almond_temp <- clim %>% 
  filter(month == 2) %>% 
  group_by(year) %>% 
  summarize(mean_min_temp = mean(tmin_c)) %>% 
  select(year, mean_min_temp)

# find precipitation in January
almond_precip <- clim %>% 
  filter(month == 1) %>% 
  group_by(year) %>% 
  summarize(sum_precip = sum(precip)) %>% 
  select(year, sum_precip)

clim_new <- left_join(almond_temp, almond_precip,
                      by = c("year" = "year"))
```


```{r}
yield <- gen_almond_yield(year = clim_new$year, 
                          precip = clim_new$sum_precip,
                          temp = clim_new$mean_min_temp)
```


```{r}
almond_profit <- compute_almond_profit(gen_almond_yield = yield$gen_almond_yield,
                                       year = yield$year,
                                       price = 1000,
                                       discount_rate = 0.15)
```

```{r}
deviation = .15
base_a = 0.015
base_c = 0.07
nsamples = 300

a = runif(min=base_a-deviation*base_a,
                max = base_a+deviation*base_a, n=nsamples)

c = runif(min=base_c-deviation*base_c,
                max = base_c+deviation*base_c, n=nsamples)
params = tibble(a, c)

results <- params %>% 
  pmap(gen_almond_yield, 
       year = clim_new$year,
       precip = clim_new$sum_precip,
       temp = clim_new$mean_min_temp)
tmp = map_df(results, `[`)
```

```{r}
ggplot(data = tmp, aes(x = year, y = gen_almond_yield)) +
  geom_point()
```

```{r}
ggplot(data = tmp, aes(x = year, y = gen_almond_yield, group = year))+
  geom_boxplot()
```

 
```{r}
deviation = 500
base_price = 0.015
nsamples = 300

price = runif(min=base_price-deviation*base_price,
                max = base_price+deviation*base_price, n=nsamples)
params = tibble(price)

price_results <- params %>% 
  pmap(compute_almond_profit, 
       gen_almond_yield = tmp$gen_almond_yield,
       year = tmp$year,
       discount_rate = 0.15)
price_results_df = map_df(price_results, `[`)
```

```{r}
ggplot(data = price_results_df, aes(x = year, y = npv, group = year)) +
  geom_boxplot()
```







